### ISSUE TITLE
OTR issue when requesting presence authorization

### ISSUE THREAD

**Issue by cfcs** [hannesm/jackline#59] opened 2015-06-08 18:47 UTC
I type:

```
hello
/authorization request
test
```

Results in:
```
19:36:07 ?O> hello
19:36:09 *** has been asked to sent presence updates to you
19:36:10 ***OTR Warning*** didn't sent message, there was no encrypted connection: test
19:36:10 ***OTR warning*** OTR error Malformed OTR data message: type
```

This is repeatable, any clue what's going on here?

My contact is using Pidgin. :-(

**Comment by hannesm** [comment] 2015-06-24 15:48
this is certainly caused by confusion to which resource a message was sent. what is your otr policy? (esp: do you require encryption?)

**Comment by cfcs** [comment] 2015-06-24 16:21
yes, i believe so. v2, v3, whitespace, require encryption, automatically start (i think, dont have jackline here)

**Comment by hannesm** [comment] 2015-06-24 16:28
with require encryption the `hello` shouldn't appear.. https://github.com/hannesm/jackline/blob/master/cli/cli_client.ml#L684-L685

**Comment by cfcs** [comment] 2015-06-24 16:52
Hence my confusion.

**Comment by hannesm** [comment] 2015-08-23 21:17
plz reopen if still the case now that #73 is merged

**Closed by hannesm** 2015-08-23 21:17 UTC
