### ISSUE TITLE
Simutanously running jacklines disconnect each other

### ISSUE THREAD

**Issue by sternenseemann** [hannesm/jackline#175] opened 2017-09-09 11:19 UTC
## Reproduction

* two connected jacklines using the same config (`26688f07c3edc3b83e7aa0b9136cd1e9dcb58ed5` and `0a1e4ea23245633fe23edf09b2309659a1bc3649`, will do further testing)
* xmpp server is prosody
* start an OTR session

## Result

* one of the two (the one I started last) reconnects because of a Xml parse error.

I'll try to reproduce this issue further and post it here.

**Comment by infinity0** [comment] 2017-09-09 13:49
This is possibly because they are using the same jabber resource (jid user@domain/resource), servers will automatically disconnect one client if two connect with the same resource. The fix is to either make jackline support a jid without a resource, or you need to manually edit the configs to have different jids.

**Comment by hannesm** [comment] 2017-09-09 15:58
as @infinity0 said, the workaround is to have two different configs (using a different `resource`).

the other option, to let the server choose the resource for you, is not implemented yet, and tracked as #155 in this issue tracker.

closing this issue since it is the expected behaviour with the current implementation.

**Closed by hannesm** 2017-09-09 15:58 UTC

**Comment by sternenseemann** [comment] 2017-09-09 17:26
I see!

I guess the only thing to improve here is the error message? It is a bit misleading to have a `async` Xml parse error instead of being told, that the server disconnected the client actively.

**Comment by hannesm** [comment] 2017-09-09 18:33
yes, making the error message more clear would be great.  unfortunately this is and exception raised deep inside the xml library and I'm atm not sure how to improve it (without rewriting the xml&xmpp interface, as indicated in https://hannes.nqsb.io/Posts/Jackline)
